src/java/udem/edu/co/controller/VehiculosController.java
package udem.edu.co.controller;

import udem.edu.co.entidades.Vehiculos;
import udem.edu.co.controller.util.JsfUtil;
import udem.edu.co.controller.util.PaginationHelper;
import udem.edu.co.facade.VehiculosFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("vehiculosController")
@SessionScoped
public class VehiculosController implements Serializable {

    private Vehiculos current;
    private DataModel items = null;
    @EJB
    private udem.edu.co.facade.VehiculosFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public VehiculosController() {
    }

    public Vehiculos getSelected() {
        if (current == null) {
            current = new Vehiculos();
            selectedItemIndex = -1;
        }
        return current;
    }

    private VehiculosFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Vehiculos) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Vehiculos();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("VehiculosCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Vehiculos) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("VehiculosUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Vehiculos) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("VehiculosDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Vehiculos getVehiculos(java.lang.Integer id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Vehiculos.class)
    public static class VehiculosControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            VehiculosController controller = (VehiculosController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "vehiculosController");
            return controller.getVehiculos(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Vehiculos) {
                Vehiculos o = (Vehiculos) object;
                return getStringKey(o.getId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Vehiculos.class.getName());
            }
        }

    }

}

web/vehiculos/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateVehiculosTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateVehiculosLabel_id}" for="id" />
                    <h:inputText id="id" value="#{vehiculosController.selected.id}" title="#{bundle.CreateVehiculosTitle_id}" required="true" requiredMessage="#{bundle.CreateVehiculosRequiredMessage_id}"/>
                    <h:outputLabel value="#{bundle.CreateVehiculosLabel_tipo}" for="tipo" />
                    <h:inputText id="tipo" value="#{vehiculosController.selected.tipo}" title="#{bundle.CreateVehiculosTitle_tipo}" />
                    <h:outputLabel value="#{bundle.CreateVehiculosLabel_placa}" for="placa" />
                    <h:inputText id="placa" value="#{vehiculosController.selected.placa}" title="#{bundle.CreateVehiculosTitle_placa}" />
                    <h:outputLabel value="#{bundle.CreateVehiculosLabel_estacion}" for="estacion" />
                    <h:inputText id="estacion" value="#{vehiculosController.selected.estacion}" title="#{bundle.CreateVehiculosTitle_estacion}" />
                    <h:outputLabel value="#{bundle.CreateVehiculosLabel_estado}" for="estado" />
                    <h:inputText id="estado" value="#{vehiculosController.selected.estado}" title="#{bundle.CreateVehiculosTitle_estado}" />
                </h:panelGrid>
                <br />
                <h:commandLink action="#{vehiculosController.create}" value="#{bundle.CreateVehiculosSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{vehiculosController.prepareList}" value="#{bundle.CreateVehiculosShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateVehiculosIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/vehiculos/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditVehiculosTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditVehiculosLabel_id}" for="id" />
                    <h:inputText id="id" value="#{vehiculosController.selected.id}" title="#{bundle.EditVehiculosTitle_id}" required="true" requiredMessage="#{bundle.EditVehiculosRequiredMessage_id}"/>
                    <h:outputLabel value="#{bundle.EditVehiculosLabel_tipo}" for="tipo" />
                    <h:inputText id="tipo" value="#{vehiculosController.selected.tipo}" title="#{bundle.EditVehiculosTitle_tipo}" />
                    <h:outputLabel value="#{bundle.EditVehiculosLabel_placa}" for="placa" />
                    <h:inputText id="placa" value="#{vehiculosController.selected.placa}" title="#{bundle.EditVehiculosTitle_placa}" />
                    <h:outputLabel value="#{bundle.EditVehiculosLabel_estacion}" for="estacion" />
                    <h:inputText id="estacion" value="#{vehiculosController.selected.estacion}" title="#{bundle.EditVehiculosTitle_estacion}" />
                    <h:outputLabel value="#{bundle.EditVehiculosLabel_estado}" for="estado" />
                    <h:inputText id="estado" value="#{vehiculosController.selected.estado}" title="#{bundle.EditVehiculosTitle_estado}" />
                </h:panelGrid>
                <h:commandLink action="#{vehiculosController.update}" value="#{bundle.EditVehiculosSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditVehiculosViewLink}"/>
                <br />
                <h:commandLink action="#{vehiculosController.prepareList}" value="#{bundle.EditVehiculosShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditVehiculosIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/vehiculos/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListVehiculosTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListVehiculosEmpty}" rendered="#{vehiculosController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{vehiculosController.items.rowCount > 0}">
                    <h:outputText value="#{vehiculosController.pagination.pageFirstItem + 1}..#{vehiculosController.pagination.pageLastItem + 1}/#{vehiculosController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{vehiculosController.previous}" value="#{bundle.Previous} #{vehiculosController.pagination.pageSize}" rendered="#{vehiculosController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{vehiculosController.next}" value="#{bundle.Next} #{vehiculosController.pagination.pageSize}" rendered="#{vehiculosController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{vehiculosController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListVehiculosTitle_id}"/>
                            </f:facet>
                            <h:outputText value="#{item.id}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListVehiculosTitle_tipo}"/>
                            </f:facet>
                            <h:outputText value="#{item.tipo}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListVehiculosTitle_placa}"/>
                            </f:facet>
                            <h:outputText value="#{item.placa}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListVehiculosTitle_estacion}"/>
                            </f:facet>
                            <h:outputText value="#{item.estacion}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListVehiculosTitle_estado}"/>
                            </f:facet>
                            <h:outputText value="#{item.estado}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{vehiculosController.prepareView}" value="#{bundle.ListVehiculosViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{vehiculosController.prepareEdit}" value="#{bundle.ListVehiculosEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{vehiculosController.destroy}" value="#{bundle.ListVehiculosDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{vehiculosController.prepareCreate}" value="#{bundle.ListVehiculosCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListVehiculosIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/vehiculos/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewVehiculosTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewVehiculosLabel_id}"/>
                    <h:outputText value="#{vehiculosController.selected.id}" title="#{bundle.ViewVehiculosTitle_id}"/>
                    <h:outputText value="#{bundle.ViewVehiculosLabel_tipo}"/>
                    <h:outputText value="#{vehiculosController.selected.tipo}" title="#{bundle.ViewVehiculosTitle_tipo}"/>
                    <h:outputText value="#{bundle.ViewVehiculosLabel_placa}"/>
                    <h:outputText value="#{vehiculosController.selected.placa}" title="#{bundle.ViewVehiculosTitle_placa}"/>
                    <h:outputText value="#{bundle.ViewVehiculosLabel_estacion}"/>
                    <h:outputText value="#{vehiculosController.selected.estacion}" title="#{bundle.ViewVehiculosTitle_estacion}"/>
                    <h:outputText value="#{bundle.ViewVehiculosLabel_estado}"/>
                    <h:outputText value="#{vehiculosController.selected.estado}" title="#{bundle.ViewVehiculosTitle_estado}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{vehiculosController.destroyAndView}" value="#{bundle.ViewVehiculosDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewVehiculosEditLink}"/>
                <br />
                <h:commandLink action="#{vehiculosController.prepareCreate}" value="#{bundle.ViewVehiculosCreateLink}" />
                <br />
                <h:commandLink action="#{vehiculosController.prepareList}" value="#{bundle.ViewVehiculosShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewVehiculosIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>